// <auto-generated />
using System;
using GymApp_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymApp_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115214710_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("ExercisesExerciseID")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroupsMuscleGroupID")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesExerciseID", "MuscleGroupsMuscleGroupID");

                    b.HasIndex("MuscleGroupsMuscleGroupID");

                    b.ToTable("ExerciseMuscleGroup");
                });

            modelBuilder.Entity("GymApp_backend.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseID"));

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseID = 1,
                            EquipmentType = 1,
                            Name = "Bench press"
                        },
                        new
                        {
                            ExerciseID = 2,
                            EquipmentType = 2,
                            Name = "Dumbbell curl"
                        },
                        new
                        {
                            ExerciseID = 3,
                            EquipmentType = 4,
                            Name = "Preacher curl machine"
                        },
                        new
                        {
                            ExerciseID = 4,
                            EquipmentType = 3,
                            Name = "Kettlebell swings"
                        },
                        new
                        {
                            ExerciseID = 5,
                            EquipmentType = 0,
                            Name = "Push-ups"
                        });
                });

            modelBuilder.Entity("GymApp_backend.Models.MuscleGroup", b =>
                {
                    b.Property<int>("MuscleGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MuscleGroupID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MuscleGroupID");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("GymApp_backend.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("PostType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test description",
                            IsPrivate = false,
                            PostType = 0,
                            Title = "My first workout",
                            UserID = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("GymApp_backend.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "aaa",
                            Role = 2,
                            Username = "lander"
                        },
                        new
                        {
                            UserID = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "aaa",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserID = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "aaa",
                            Role = 0,
                            Username = "user1"
                        },
                        new
                        {
                            UserID = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "aaa",
                            Role = 0,
                            Username = "user2"
                        },
                        new
                        {
                            UserID = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "aaa",
                            Role = 0,
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("GymApp_backend.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutID"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkoutID");

                    b.HasIndex("PostID")
                        .IsUnique();

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            WorkoutID = 1,
                            EndTime = new DateTime(2025, 11, 15, 2, 0, 0, 0, DateTimeKind.Utc),
                            PostID = 1,
                            StartTime = new DateTime(2025, 11, 15, 1, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GymApp_backend.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutExerciseID"));

                    b.Property<int>("ExerciseID")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseNotes")
                        .HasColumnType("text");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersetID")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutID")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutExerciseID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("WorkoutID");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            WorkoutExerciseID = 1,
                            ExerciseID = 1,
                            ExerciseOrder = 0,
                            WorkoutID = 1
                        },
                        new
                        {
                            WorkoutExerciseID = 2,
                            ExerciseID = 2,
                            ExerciseOrder = 1,
                            WorkoutID = 1
                        });
                });

            modelBuilder.Entity("GymApp_backend.Models.WorkoutSet", b =>
                {
                    b.Property<int>("WorkoutSetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutSetID"));

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SetType")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKG")
                        .HasColumnType("numeric");

                    b.Property<int>("WorkoutExerciseID")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutSetID");

                    b.HasIndex("WorkoutExerciseID");

                    b.ToTable("workoutSets");

                    b.HasData(
                        new
                        {
                            WorkoutSetID = 1,
                            Reps = 15,
                            SetOrder = 0,
                            SetType = 0,
                            WeightKG = 20m,
                            WorkoutExerciseID = 1
                        },
                        new
                        {
                            WorkoutSetID = 2,
                            Reps = 12,
                            SetOrder = 1,
                            SetType = 0,
                            WeightKG = 40m,
                            WorkoutExerciseID = 1
                        },
                        new
                        {
                            WorkoutSetID = 3,
                            Reps = 10,
                            SetOrder = 2,
                            SetType = 0,
                            WeightKG = 60m,
                            WorkoutExerciseID = 1
                        },
                        new
                        {
                            WorkoutSetID = 4,
                            Reps = 15,
                            SetOrder = 0,
                            SetType = 0,
                            WeightKG = 15m,
                            WorkoutExerciseID = 2
                        },
                        new
                        {
                            WorkoutSetID = 5,
                            Reps = 12,
                            SetOrder = 1,
                            SetType = 0,
                            WeightKG = 20m,
                            WorkoutExerciseID = 2
                        });
                });

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.HasOne("GymApp_backend.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp_backend.Models.MuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupsMuscleGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymApp_backend.Models.Post", b =>
                {
                    b.HasOne("GymApp_backend.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp_backend.Models.Workout", b =>
                {
                    b.HasOne("GymApp_backend.Models.Post", "Post")
                        .WithOne("Workout")
                        .HasForeignKey("GymApp_backend.Models.Workout", "PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("GymApp_backend.Models.WorkoutExercise", b =>
                {
                    b.HasOne("GymApp_backend.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp_backend.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymApp_backend.Models.WorkoutSet", b =>
                {
                    b.HasOne("GymApp_backend.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("GymApp_backend.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("GymApp_backend.Models.Post", b =>
                {
                    b.Navigation("Workout")
                        .IsRequired();
                });

            modelBuilder.Entity("GymApp_backend.Models.User", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("GymApp_backend.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("GymApp_backend.Models.WorkoutExercise", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
